name: PR

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ktlint
        uses: "vroy/gha-kotlin-linter@v1"
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ./gradlew build
