name: Test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: ./gradlew jvmTest

      - name: Archive redux-kotlin-thunk Test Reports
        uses: actions/upload-artifact@v1
        with:
          name: redux-kotlin-thunk_test_reports
          path: build/reports/tests
